name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Replace with your Node.js version

      - name: Install npm dependencies
        run: npm install

      - name: Build the Angular app
        run: ng build --prod
        # Replace '--prod' with appropriate build command options for your project

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          app_location: "/" # The location of your app code
          api_location: "" # The location of your API code (if applicable)
          output_location: "dist/final-project-frontend" # The build output directory
